name: Deploy to S3 and invalidate CloudFront distribution
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.5
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.5
      - name: Build with Gradle
        run: cd server && gradle build

      - name: Terraform Init
        id: init
        run: cd terraform && terraform init
        env:
          TF_ACTION_WORKING_DIR: "terraform"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Validate
        id: validate
        run: cd terraform && terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: cd terraform && terraform plan -out=tfplan -input=false
        env:
          TF_ACTION_WORKING_DIR: "terraform"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Apply
        id: apply
        run: cd terraform && terraform apply -input=false tfplan
        continue-on-error: true
        env:
          TF_ACTION_WORKING_DIR: "terraform"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
