name: Deploy to S3 and invalidate CloudFront distribution
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.5
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.5
      - name: Where am I
        run: ls && cd .. && ls && cd .. && ls && cd .. && ls && cd .. && ls
      - name: server folder
        run: cd server && ls
      - name: Build with Gradle
        run: gradle build --file **/gradle-wrapper.jar
      - name: Test with Gradle
        run: gradle test
