name: Deploy to S3 and invalidate CloudFront distribution
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.5
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.5
      - name: Build with Gradle
        run: cd server && gradle build
