name: Deploy to S3 and invalidate CloudFront distribution
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: cd ../../server && gradle test