name: Deploy to S3 and invalidate CloudFront distribution
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: pwd && echo ${GITHUB_WORKSPACE} && ls && cd ./scheduland && ls